"""empty message

Revision ID: 413919cf3d6e
Revises: 
Create Date: 2018-08-23 21:57:57.819711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '413919cf3d6e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctorId', sa.Integer(), nullable=False),
    sa.Column('locationId', sa.Integer(), nullable=False),
    sa.Column('startTime', sa.DateTime(), nullable=False),
    sa.Column('endTime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctorId'], ['doctor.id'], ),
    sa.ForeignKeyConstraint(['locationId'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doctorLocationAssociation',
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doctorLocationAssociation')
    op.drop_table('appointment')
    op.drop_table('location')
    op.drop_table('doctor')
    # ### end Alembic commands ###
