"""empty message

Revision ID: efa39f9dcea9
Revises: 413919cf3d6e
Create Date: 2018-08-28 13:51:12.316817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efa39f9dcea9'
down_revision = '413919cf3d6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('isCanceled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointment', 'isCanceled')
    # ### end Alembic commands ###
